# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l43fUF7JiI_C0pk2FRsjtLdns0PJxSYR
"""

import math

"""# Noktaların tanımlanması"""

points = [(1, 2), (3, 4), (5, 6), (7, 8), (2, 3)]

"""# Öklid mesafesi hesaplayan fonksiyon"""

def euclideanDistance(point1, point2):
    return math.sqrt((point2[0] - point1[0]) ** 2 + (point2[1] - point1[1]) ** 2)

"""# Mesafelerin hesaplanması"""

distances = []
for i in range(len(points)):
    for j in range(i + 1, len(points)):
        distances.append(euclideanDistance(points[i], points[j]))

"""# Minimum mesafenin bulunması"""

min_distance = min(distances)

"""# Sonuçları yazdırma"""

print("Hesaplanan mesafeler:", distances)
print("Minimum mesafe:", min_distance)